---
allowBuilds:
  '@swc/core': true
  '@tailwindcss/oxide': true
  'esbuild': true
blockExoticSubdeps: true
minimumReleaseAge: 10080 # 7 days
minimumReleaseAgeExclude:
  - '@douglasneuroinformatics/*'
